# Generated by Django 5.1.6 on 2025-06-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskdetail_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='assigned_to',
            field=models.CharField(default='David Anderson', max_length=100),
        ),
    ]
