# Generated by Django 5.1.6 on 2026-03-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
