# Generated by Django 5.1.6 on 2026-03-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/No_Image_Available.jpg', null=True, upload_to='task_asset'),
        ),
    ]
